version: '3.7'

services:
  aws:
    image: abdennour/aws
    volumes:
      - .:/code
      - aws-creds:/root/.aws
    restart: "no"
    working_dir: /code

volumes:
  aws-creds:
    name: aws-creds
